import banner from "../../assets/ranting-web-banner.png";
import icon from "../../assets/ranting-icon.png";
import club from "../../assets/cblub-placeholder.png";
import branch from "../../assets/branch-placeholder.png";
import student from "../../assets/student-parent-placeholder.png";
import emptyBranches from "../../assets/no-branch-yet.png";
import emptyStudents from "../../assets/no-student-yet.png";
import coach from "../../assets/coach-placeholder.png";
import ledger from "../../assets/no-payment-yet.png";
export const assets = { banner, icon, club, branch, student, emptyBranches, emptyStudents, coach, ledger };
